### ISSUE TITLE
Volume Control Slider Icon

### ISSUE THREAD

**Issue by R3mb0** [yanniz0r/sonq#12]
Volume Control Slider Icon should change depending on volume value

**Comment by R3mb0** [comment]
![Screenshot_2021-03-18 Screenshot](https://user-images.githubusercontent.com/29989306/111613493-dd497380-87de-11eb-91f7-9ab9885b98f3.png)
![Screenshot_2021-03-18 Screenshot(1)](https://user-images.githubusercontent.com/29989306/111613496-de7aa080-87de-11eb-8c3f-6780401d93c3.png)
![Screenshot_2021-03-18 Screenshot(2)](https://user-images.githubusercontent.com/29989306/111613573-f3573400-87de-11eb-9808-6107511ee228.png)

There are just two icons, we could use other icons then those of font awesome.
There is a missing middle state.

**Comment by yanniz0r** [comment]
Love it!

**Comment by yanniz0r** [comment]
PR merged, thanks!
