### ISSUE TITLE
Some Bugs.... 

### ISSUE THREAD

**Issue by Maximilian1021** [yanniz0r/sonq#16]
- [x]  Die **Entertaste** bei der Playlist suche startet das Spiel (Man kommt zur "_Spielernamen_" eingabe). Es wurde aktiv aber keine Playlist ausgewählt, bzw man weiß nicht ob eine Playlist ausgewählt wurde 

- [x]  Spielt man allein, und das Ergebnis wurde richtig getippt, kommt man ja zum "Ergebnisscreen" Dort läuft die Musik weiter bis der Preview fertig ist. Ein automatisches Stoppen wenn alle das richtige Ergebnis haben wäre super. 

- [X] Der Countdown wo zeigt wie lange man noch Zeit zum raten hat stoppt bereits bei ca. 4 Sekunden und schickt einen ins Ergebnissmenü wenn keiner es errät (Spiele aktuell allein)

**Comment by yanniz0r** [comment]
The issue regarding the countdown is done!

**Comment by yanniz0r** [comment]
Done!
