### ISSUE TITLE
English translations

### ISSUE THREAD

**Issue by yanniz0r** [yanniz0r/sonq#20]
Add english translations and implement language detection

**Comment by R3mb0** [comment]
I am detecting the language in the backend by using @unly/universal-language-detector. But i change the language in the front end which causes an error:
![grafik](https://user-images.githubusercontent.com/29989306/110208722-29b0bd00-7e89-11eb-8ce9-fe088ad66e3b.png)

Is there a way to change the initial language on the serverside?

**Comment by yanniz0r** [comment]
There are some places where you can access the request and therefore its headers. For example the getInitialProps methods (eg. in the _app.js) or in the custom document of next js

**Comment by R3mb0** [comment]
This is what @unly/universal-language-detector does.
So im trying to pass the detected language directly into i18n.
And it works, but it also throws the error from the first comment.

``` javascript import i18next from "i18next";
import { initReactI18next } from "react-i18next";
import en from "./en";
import de from "./de";

import { universalLanguageDetect } from "@unly/universal-language-detector";

const lang = universalLanguageDetect({
  supportedLanguages: ["en", "de"],
  fallbackLanguage: "en",
  errorHandler: (err) => {
    console.log(err);
  },
});

i18next
  .use(initReactI18next) // passes i18n down to react-i18next
  .init({
    resources: {
      en,
      de,
    },
    lng: lang,
    fallbackLng: "en",
    ns: [...Object.keys(de)],
    interpolation: {
      escapeValue: false,
    },
    debug: true,
  });
```

**Comment by yanniz0r** [comment]
You have to detect the locale somewhere where you have access to the requests headers. Maybe this helps: https://nextjs.org/docs/advanced-features/i18n-routing

**Comment by yanniz0r** [comment]
Done!
