### ISSUE TITLE
Some "Bugs"

### ISSUE THREAD

**Issue by Maximilian1021** [yanniz0r/sonq#43]
- Übersetzungsfehler auf der Hauptseite:

![image](https://user-images.githubusercontent.com/13157092/114171364-7b3ee280-9934-11eb-9b34-645c14081a6b.png)

- Spotify Redirect Error - Wenn man auf "Abbrechen" drückt kommt man auch auf die "Erstelle Spiel Seite" was ja aber nicht funktioniert :)
![image](https://img.game-energy.de/dsyBsniVW0.gif)

**Comment by yanniz0r** [comment]
Fixed!
