### ISSUE TITLE
Explain game on landing page

### ISSUE THREAD

**Issue by yanniz0r** [yanniz0r/sonq#5]
In order to give the user an impression of what they have to expect, a detailed game description should be on the landing page. It should allow the user to understand how the game works, what interactions are required and what the rules are

**Comment by R3mb0** [comment]
May you share the screenshots you made? I think those are a great way to visualy show the user how playing the game is like.

**Comment by yanniz0r** [comment]
Of course, I will as soon as I'm back on my Ubuntu device :)
